# -*- coding: utf-8 -*-
"""6. Trend & Seasonality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QeoFprC8PKv3NNKbi15-ojDI830d57L3
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
from matplotlib.pylab import plt
from sklearn.preprocessing import MinMaxScaler

import pandas as pd
import numpy as np
import statsmodels

import statsmodels.api as sm

import statsmodels
print(statsmodels.__version__)
print(np.__version__)
print(pd.__version__)

xls = pd.ExcelFile('dataset.xlsx')
df = pd.read_excel(xls, 'sost')

df['Time'] = pd.to_datetime(df['Time'],format='%Y-%m-%d')

df = df.set_index("Time").asfreq('d')

"""Рассмотрим среднее значение по месяцам"""

# first test, informally, plot the moving average
# note the ROLLING function
df.rolling(window = 30).mean().plot()

# How can we see whether the variance changes over time?

# Can you plot the autocorrelation?
from statsmodels.tsa.stattools import acf

series = df['Amount']

df = df.dropna()

df.index

"""Извлекаем циклы и тренды из данного датасета"""

cycle, trend = sm.tsa.filters.hpfilter(series, 365)
fig, ax = plt.subplots(3,1)
ax[0].plot(series)
ax[0].set_title('Amount')
ax[1].plot(trend)
ax[1].set_title('Trend')
ax[2].plot(cycle)
ax[2].set_title('Cycle')
plt.show()

